//! In-memory row shape for persisted trace calls.

/// One persisted trace call — the in-memory mirror of a `trace_calls` row.
pub(super) struct TraceRow {
    pub(super) id: String,
    pub(super) created_at: i64,
    pub(super) provider: String,
    pub(super) method: String,
    pub(super) path: String,
    pub(super) model: String,
    pub(super) status_code: i64,
    pub(super) cache_status: String,
    pub(super) latency_ms: i64,
    pub(super) request_id: String,
    pub(super) prompt_system: String,
    pub(super) prompt_user: String,
    pub(super) response_text: String,
    pub(super) response_language: String,
    pub(super) error_code: Option<String>,
    pub(super) error_message: Option<String>,
    pub(super) error_detail: Option<String>,
    pub(super) tokens_in: i64,
    pub(super) tokens_out: i64,
    pub(super) cost: String,
    pub(super) temperature: Option<f64>,
    pub(super) trace_id: String,
    pub(super) parent_span_id: Option<String>,
    pub(super) tool_use_ids: String,
    pub(super) context_inputs: String,
    pub(super) input_hash: String,
    pub(super) stale: bool,
    pub(super) request_body: Vec<u8>,
    pub(super) request_target: String,
    pub(super) tool_result_ids: Vec<String>,
}
