//! In-memory row shape for persisted trace calls.

/// One persisted trace call — the in-memory mirror of a `trace_calls` row.
pub(super) struct TraceRow {
    pub(crate) id: String,
    pub(crate) created_at: i64,
    pub(crate) provider: String,
    pub(crate) method: String,
    pub(crate) path: String,
    pub(crate) model: String,
    pub(crate) status_code: i64,
    pub(crate) cache_status: String,
    pub(crate) latency_ms: i64,
    pub(crate) request_id: String,
    pub(crate) prompt_system: String,
    pub(crate) prompt_user: String,
    pub(crate) response_text: String,
    pub(crate) response_language: String,
    pub(crate) error_code: Option<String>,
    pub(crate) error_message: Option<String>,
    pub(crate) error_detail: Option<String>,
    pub(crate) tokens_in: i64,
    pub(crate) tokens_out: i64,
    pub(crate) cost: String,
    pub(crate) temperature: Option<f64>,
    pub(crate) trace_id: String,
    pub(crate) parent_span_id: Option<String>,
    pub(crate) tool_use_ids: String,
    pub(crate) context_inputs: String,
    pub(crate) input_hash: String,
    pub(crate) stale: bool,
    pub(crate) is_replay: bool,
    pub(crate) replay_source_id: Option<String>,
    pub(crate) replay_provider: Option<String>,
    pub(crate) request_body: Vec<u8>,
    pub(crate) request_target: String,
    pub(crate) workspace_id: String,
    pub(crate) tool_result_ids: Vec<String>,
}
